export const models = [
    "ICBINP - I Can't Believe It's Not Photography",
    "AlbedoBase XL (SDXL)",
    "Deliberate",
    "Anything Diffusion",
    "BB95 Furry Mix",
    "Pony Diffusion XL",
    "stable_diffusion",
    "SDXL 1.0",
    "Dreamshaper",
    "Stable Cascade 1.0",
    "Juggernaut XL",
    "Counterfeit",
    "Hentai Diffusion",
    "iCoMix",
    "URPM",
    "majicMIX realistic",
    "CamelliaMix 2.5D",
    "ICBINP XL",
    "DreamShaper XL",
    "Abyss OrangeMix",
    "Babes",
    "ChilloutMix",
    "Fustercluck",
    "RealBiter",
    "Western Animation Diffusion",
    "AbyssOrangeMix-AfterDark",
    "Hassaku",
    "Epic Diffusion",
    "Animagine XL",
    "BRA",
    "MeinaMix",
    "Deliberate 3.0",
    "Rev Animated",
    "Realistic Vision",
    "Cheyenne",
    "Dark Sushi Mix",
    "Unstable Diffusers XL",
    "ToonYou",
    "Realisian",
    "Grapefruit Hentai",
    "Dreamlike Photoreal",
    "Cetus-Mix",
    "Anything v5",
    "Anime Illust Diffusion XL",
    "CyberRealistic",
    "Anygen",
    "HRL",
    "GhostMix",
    "Lawlas's yiff mix",
    "stable_diffusion_inpainting",
    "Aurora",
    "Project Unreal Engine 5",
    "NeverEnding Dream",
    "AnyLoRA",
    "Pretty 2.5D",
    "Edge Of Realism",
    "Henmix Real",
    "Disney Pixar Cartoon Type A",
    "PFG",
    "Woop-Woop Photo",
    "Anything v3",
    "3DKX",
    "Poison",
    "FaeTastic",
    "waifu_diffusion",
    "Liberty",
    "Fluffusion",
    "ACertainThing",
    "PPP",
    "Experience",
    "Comic-Diffusion",
    "Pastel Mix",
    "Deliberate Inpainting",
    "stable_diffusion_2.1",
    "Analog Madness",
    "HASDX",
    "GuoFeng",
    "ExpMix Line",
    "Lyriel",
    "Reliberate",
    "Colorful",
    "RPG",
    "Perfect World",
    "DucHaiten Classic Anime",
    "Yiffy",
    "Dreamlike Diffusion",
    "CyriousMix",
    "Something",
    "BweshMix",
    "OpenJourney Diffusion",
    "526Mix-Animated",
    "Eimis Anime Diffusion",
    "Laolei New Berry Protogen Mix",
    "DucHaiten",
    "Realism Engine",
    "Neurogen",
    "MoonMix Fantasy",
    "Zeipher Female Model",
    "Healy's Anime Blend",
    "Ether Real Mix",
    "Dungeons n Waifus",
    "Ranma Diffusion",
    "Real Dos Mix",
    "Elysium Anime",
    "Hassanblend",
    "GorynichMix",
    "Realistic Vision Inpainting",
    "Galena Redux",
    "Kenshi",
    "Dungeons and Diffusion",
    "AIO Pixel Art",
    "SD-Silicon",
    "Zack3D",
    "Anything Diffusion Inpainting",
    "Furry Epoch",
    "UMI Olympus",
    "Jim Eidomode",
    "Inkpunk Diffusion",
    "Graphic-Art",
    "iCoMix Inpainting",
    "Anime Pencil Diffusion",
    "ProtoGen",
    "BPModel",
    "SweetBoys 2D",
    "Openniji",
    "DreamShaper Inpainting",
    "Midjourney PaintArt",
    "Epic Diffusion Inpainting",
    "VinteProtogenMix",
    "Dark Victorian Diffusion",
    "Dan Mumford Style",
    "Elldreth's Lucid Mix",
    "Movie Diffusion",
    "GTA5 Artwork Diffusion",
    "Protogen Anime",
    "AAM XL",
    "Analog Diffusion",
    "Mistoon Amethyst",
    "Uhmami",
    "Pulp Vector Art",
    "Moedel",
    "Protogen Infinity",
    "MoistMix",
    "GuFeng",
    "Unstable Ink Dream",
    "DGSpitzer Art Diffusion",
    "Trinart Characters",
    "Ghibli Diffusion",
    "A-Zovya RPG Inpainting",
    "Classic Animation Diffusion",
    "Art Of Mtg",
    "Ultraskin",
    "Vector Art",
    "Cheese Daddys Landscape Mix",
    "Illuminati Diffusion",
    "Quiet Goodnight XL",
    "ModernArt Diffusion",
    "App Icon Diffusion",
    "DreamLikeSamKuvshinov",
    "DnD Map Generator",
    "Microcritters",
    "PortraitPlus",
    "ChromaV5",
    "Mega Merge Diffusion",
    "Microworlds",
    "Char",
    "Disco Elysium",
    "Fantasy Card Diffusion",
    "vectorartz",
    "Nitro Diffusion",
    "CharHelper",
    "Double Exposure Diffusion",
    "Samaritan 3d Cartoon",
    "Funko Diffusion",
    "Sci-Fi Diffusion",
    "DnD Item",
    "AbsoluteReality",
    "JWST Deep Space Diffusion",
    "Seek.art MEGA",
    "Robo-Diffusion",
    "Papercut Diffusion",
    "JoMad Diffusion",
    "Tron Legacy Diffusion",
    "Pokemon3D",
    "Photon",
];
