/** @type {import('tailwindcss').Config} */
const lightTheme = require("daisyui/src/colors/themes")["[data-theme=light]"];
const darkTheme = require("daisyui/src/colors/themes")["[data-theme=dark]"];
console.log(darkTheme);
module.exports = {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "node_modules/daisyui/dist/**/*.js",
        "node_modules/react-daisyui/dist/**/*.js",
    ],
    theme: {
        extend: {
            colors: {
                "fire-1": "#f63c01",
                "fire-2": "#f97d02",
                "fire-3": "#f8a700",
                "fire-4": "#fdda00",
                "fire-5": "#fef24f",
                "blood-1": "#870108",
                "blood-2": "#a80000",
                "blood-3": "#bd3535",
                "blood-4": "#d96161",
                "blood-5": "#feb2b2",
                "lightning-1": "#01365c",
                "lightning-2": "#08537d",
                "lightning-3": "#1378c4",
                "lightning-4": "#71d3d0",
                "lightning-5": "#b4fcd5",
                "acid-1": "#83c30a",
                "acid-2": "#cfe10c",
                "acid-3": "#ecea00",
                "acid-4": "#fefb98",
                "acid-5": "#fffeeb",
                "curse-1": "#e6158e",
                "curse-2": "#f962a9",
                "curse-3": "#faa3cd",
                "curse-4": "#fed4ed",
                "curse-5": "#fff2ff",
                "kac-steel": "#abb4c3",
                "kac-steel-light": "#f3f3f4",
                "kac-steel-dark": "#65738b",
                "kac-iron": "#121b23",
                "kac-iron-light": "#23303d",
                "kac-iron-dark": "#090f15",
                "kac-blood": "#7b001d",
                "kac-blood-light": "#e3132c",
                "kac-blood-dark": "#541423",
                "kac-fire": "#f50000",
                "kac-fire-light": "#f88b00",
                "kac-fire-dark": "#950101",
                "kac-bone": "#ecb87b",
                "kac-bone-light": "#e4ceb3",
                "kac-bone-dark": "#a3835f",
                "kac-skin": "#f7adae",
                "kac-skin-light": "#f2ced1",
                "kac-skin-dark": "#e6848c",
                "kac-gold": "#ffd23b",
                "kac-gold-light": "#fff5c0",
                "kac-gold-dark": "#f59d20",
                "kac-cloth": "#5c77b2",
                "kac-cloth-light": "#80a0bc",
                "kac-cloth-dark": "#32497b",
                "kac-curse": "#f20170",
                "kac-curse-light": "#ff6883",
                "kac-curse-dark": "#c10045",
                "kac-monster": "#4ec342",
                "kac-monster-light": "#a4e9a4",
                "kac-monster-dark": "#1aa62b",
            },
            fontFamily: {
                dtHeading: ["Germania One", "sans-serif"],
                kacBody: ["Shadows Into Light Two", "cursive"],
                kacHeading: ["Trade Winds", "sans-serif"],
            },
        },
    },
    daisyui: {
        themes: [
            "light",
            "dark",
            {
                DungeonTimePrototype: {
                    ...lightTheme,
                    primary: "#f63c01",
                    fontFamily: "Alegreya, serif",
                },
                KickAssCardsPrototype: {
                    ...darkTheme,
                    primary: "#f50000",
                    secondary: "#4ec342",
                    accent: "#f20170",
                    neutral: "#191d24",
                    "neutral-focus": "#111318",
                    "neutral-content": "#a6adbb",
                    "base-100": "#23303d",
                    "base-200": "#121b23",
                    "base-300": "#090f15",
                    "base-content": "#ABB4C3",
                    fontFamily: "'Shadows Into Light Two', cursive",
                },
            },
        ],
    },
    plugins: [require("daisyui")],
};
