/** @type {import('tailwindcss').Config} */
const lightTheme = require("daisyui/src/colors/themes")["[data-theme=light]"];
const darkTheme = require("daisyui/src/colors/themes")["[data-theme=dark]"];
const plugin = require("tailwindcss/plugin");

module.exports = {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx,mdx}",
        "node_modules/daisyui/dist/**/*.js",
        "node_modules/react-daisyui/dist/**/*.js",
    ],
    safelist: [
        "animate-fadeIn",
        "animate-fadeOut",
        "drop-shadow-md",
        "print:drop-shadow-none",
        "print:filter-none",
        "inline-block",
        "card",
        "card-up",
    ],
    theme: {
        extend: {
            colors: {
                "fire-1": "#f63c01",
                "fire-2": "#f97d02",
                "fire-3": "#f8a700",
                "fire-4": "#fdda00",
                "fire-5": "#fef24f",
                "blood-1": "#870108",
                "blood-2": "#a80000",
                "blood-3": "#bd3535",
                "blood-4": "#d96161",
                "blood-5": "#feb2b2",
                "lightning-1": "#01365c",
                "lightning-2": "#08537d",
                "lightning-3": "#1378c4",
                "lightning-4": "#71d3d0",
                "lightning-5": "#b4fcd5",
                "acid-1": "#83c30a",
                "acid-2": "#cfe10c",
                "acid-3": "#ecea00",
                "acid-4": "#fefb98",
                "acid-5": "#fffeeb",
                "curse-1": "#e6158e",
                "curse-2": "#f962a9",
                "curse-3": "#faa3cd",
                "curse-4": "#fed4ed",
                "curse-5": "#fff2ff",
                "kac-steel": "#abb4c3",
                "kac-steel-light": "#f3f3f4",
                "kac-steel-dark": "#65738b",
                "kac-iron": "#121b23",
                "kac-iron-light": "#23303d",
                "kac-iron-dark": "#090f15",
                "kac-blood": "#7b001d",
                "kac-blood-light": "#e3132c",
                "kac-blood-dark": "#541423",
                "kac-fire": "#f50000",
                "kac-fire-light": "#f88b00",
                "kac-fire-lightest": "#ffe79b",
                "kac-fire-dark": "#950101",
                "kac-bone": "#ecb87b",
                "kac-bone-light": "#e4ceb3",
                "kac-bone-dark": "#a3835f",
                "kac-bone-darker": "#856a4c",
                "kac-skin": "#f7adae",
                "kac-skin-light": "#f2ced1",
                "kac-skin-dark": "#e6848c",
                "kac-gold": "#ffd23b",
                "kac-gold-light": "#fff5c0",
                "kac-gold-dark": "#f59d20",
                "kac-gold-darker": "#c37509",
                "kac-cloth": "#5c77b2",
                "kac-cloth-light": "#80a0bc",
                "kac-cloth-lightest": "#d8e2ea",
                "kac-cloth-dark": "#32497b",
                "kac-curse": "#f20170",
                "kac-curse-light": "#ff6883",
                "kac-curse-dark": "#c10045",
                "kac-monster": "#4ec342",
                "kac-monster-light": "#a4e9a4",
                "kac-monster-dark": "#1aa62b",
                "mm-plastic": "#FFEACB",
                "mm-plastic-light": "#FEFBED",
                "mm-steel": "#D1EBF8",
                "mm-steel-light": "#B2D5E5",
                "mm-magic-light": "#89C7FF",
                "mm-magic": "#4CA4F5",
                "mm-magic-dark": "#528FC7",
                "mm-sunset-light": "#EC938C",
                "mm-sunset": "#B27783",
                "mm-sunset-dark": "#494963",
                "jd-paper": "#E2DFD8",
                "jd-paper-alt": "#EED498",
                "jd-paper-alt-dark": "#D39C4E",
                "jd-gold-light": "#F7E0A9",
                "jd-gold": "#DF9B1C",
                "jd-gold-darker": "#C98016",
                "jd-gold-darkest": "#95531A",
                "jd-emerald-light": "#0C8A4E",
                "jd-emerald": "#114A32",
                "jd-emerald-dark": "#092018",
                "jd-ruby-light": "#CF2E4A",
                "jd-ruby": "#9F1132",
                "jd-ruby-dark": "#6C181D",
                "jd-soil": "#462D20",
                "jd-iron": "#180B06",
                "jd-shitty-text": "#401648",
                "jd-shitty-paper": "#88598F",
                "jd-shitty-paper-dark": "#2d0b3d",
                "jd-golden-text": "#FED801",
                "jd-golden-paper": "#fef1ca",
                "mk-tender": "#5a3b00",
            },
            fontSize: {
                "2xs": ["0.6rem", "0.75rem"],
                "3xs": ["0.5rem", "0.6rem"],
            },
            fontFamily: {
                "jd-logo": ["New Rocker", "sans-serif"],
                "jd-prequel-body": ["Barlow Condensed", "sans-serif"],
                "jd-heading": ["Skranji", "sans-serif"],
                "jd-body": ["Teko", "sans-serif"],
                dtHeading: ["Germania One", "sans-serif"],
                kacBody: ["Shantell Sans", "cursive"],
                kacLogo: ["Kalam", "cursive"],
                kacTitle: ["Passion One", "sans-serif"],
                kacHeading: ["Kalam", "cursive"],
                mmHeading: ["Quantico", "sans-serif"],
                mkHeading: ["Archivo Black", "sans-serif"],
                mkBody: ["Merriweather Sans", "sans-serif"],
            },
            backgroundPosition: {
                "1/3": "center 33%",
            },
            keyframes: {
                fadeIn: {
                    "0%": { opacity: 0 },
                    "100%": { opacity: 1 },
                },
                fadeOut: {
                    "0%": { opacity: 1 },
                    "100%": { opacity: 0 },
                },
                wave: {
                    "0%": { transform: "rotate(0.0deg)" },
                    "10%": { transform: "rotate(14deg)" },
                    "20%": { transform: "rotate(-8deg)" },
                    "30%": { transform: "rotate(14deg)" },
                    "40%": { transform: "rotate(-4deg)" },
                    "50%": { transform: "rotate(10.0deg)" },
                    "60%": { transform: "rotate(0.0deg)" },
                    "100%": { transform: "rotate(0.0deg)" },
                },
                breathe: {
                    "0%": { transform: "scale(0.9)" },
                    "25%": { transform: "scale(1)" },
                    "60%": { transform: "scale(0.9)" },
                    "100%": { transform: "scale(0.9)" },
                },
            },
            animation: {
                fadeIn: "fadeIn 0.6s ease-in-out",
                fadeOut: "fadeOut 0.6s ease-in-out",
                wave: "wave 0.6s linear infinite",
                breathe: "breathe 1s ease-in-out infinite",
            },
            animationDelay: {
                2000: "2000ms",
                3000: "3000ms",
                4000: "4000ms",
                5000: "5000ms",
            },
            animationDuration: {
                2000: "2000ms",
                3000: "3000ms",
                4000: "4000ms",
                5000: "5000ms",
            },
            dropShadow: {
                "md-heavy": ["0 1px 2px rgb(0 0 0 / 0.25)", "0 1px 1px rgb(0 0 0 / 0.12)"],
                "lg-heavy": ["0 10px 8px rgb(0 0 0 / 0.25)", "0 4px 3px rgb(0 0 0 / 0.12)"],
                "xl-heavy": ["0 20px 13px rgb(0 0 0 / 0.25)", "0 8px 5px rgb(0 0 0 / 0.12)"],
                "title": ["0px 1px 0px #1f081d", "0px 3px 0px #6d2648", "0px 3px 0px #1f081d"],
                "emboss": ["0px 2px 0px #1f081d"],
            },
            textShadow: {
                sm: "0 1px 2px var(--tw-shadow-color)",
                DEFAULT: "0 2px 4px var(--tw-shadow-color)",
                lg: "0 8px 16px var(--tw-shadow-color)",
            },
        },
    },
    daisyui: {
        themes: [
            "light",
            "dark",
            {
                DungeonTimePrototype: {
                    ...lightTheme,
                    primary: "#f63c01",
                    fontFamily: "Alegreya, serif",
                },
                KickAssCardsPrototype: {
                    ...darkTheme,
                    primary: "#f50000",
                    secondary: "#4ec342",
                    accent: "#f20170",
                    neutral: "#191d24",
                    "neutral-focus": "#111318",
                    "neutral-content": "#a6adbb",
                    "base-100": "#23303d",
                    "base-200": "#121b23",
                    "base-300": "#090f15",
                    "base-content": "#ABB4C3",
                    fontFamily: "'Shadows Into Light Two', cursive",
                },
            },
        ],
    },
    plugins: [
        require("@tailwindcss/typography"),
        require("tailwindcss-animate"),
        require("daisyui"),
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    "translate-z": (value) => ({
                        "--tw-translate-z": value,
                        transform: ` translate3d(var(--tw-translate-x), var(--tw-translate-y), var(--tw-translate-z)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))`,
                    }), // this is actual CSS
                },
                { values: theme("translate"), supportsNegativeValues: true }
            );
        }),
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    "text-shadow": (value) => ({
                        textShadow: value,
                    }),
                },
                { values: theme("textShadow") }
            );
        }),
    ],
};
