import { AnimationEnum, LightModeEnum } from "../types/effectTypes";
import { EffectBoardStateType } from "./effectBoardStateTypes";

export const getInitialEffectBoardState = (): EffectBoardStateType => ({
    dmxParams: {},
    effectMap: {
        blackOut: {
            slug: "blackOut",
            title: "Black Out",
            icon: "/mighty-decks/counters/incognito.png",
            lightEffect: {
                r: 0,
                g: 0,
                b: 0,
                mode: LightModeEnum.Static,
                interval: 0,
                intensity: 0,
                animation: AnimationEnum.Immediate,
                animationDuration: 0,
            },
        },
        stopAudio: {
            slug: "stopAudio",
            title: "Stop Audio",
            icon: "/mighty-decks/actors/base/civilian.png",
            soundEffect: {
                stopChannels: ["SFX", "MUSIC"],
            },
        },
        fadeToBlack: {
            slug: "fadeToBlack",
            title: "Fade to Black",
            icon: "/mighty-decks/effects/hindered.png",
            lightEffect: {
                r: 0,
                g: 0,
                b: 0,
                mode: LightModeEnum.Static,
                interval: 0,
                intensity: 0,
                animation: AnimationEnum.Transition,
                animationDuration: 1000,
            },
        },
        white: {
            slug: "White",
            title: "White",
            icon: "/mighty-decks/effects/freezing.png",
            lightEffect: {
                r: 255,
                g: 72,
                b: 20,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Transition,
                animationDuration: 1000,
            },
        },
        red: {
            slug: "Red",
            title: "Red",
            icon: "/mighty-decks/effects/injury.png",
            lightEffect: {
                r: 255,
                g: 0,
                b: 0,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Transition,
                animationDuration: 1000,
            },
        },
        green: {
            slug: "Green",
            title: "Green",
            icon: "/mighty-decks/assets/base/healing.png",
            lightEffect: {
                r: 0,
                g: 255,
                b: 0,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Transition,
                animationDuration: 1000,
            },
        },
        blue: {
            slug: "Blue",
            title: "Blue",
            icon: "/mighty-decks/effects/distress.png",
            lightEffect: {
                r: 0,
                g: 0,
                b: 255,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Transition,
                animationDuration: 1000,
            },
        },
        thunder: {
            slug: "Thunder",
            title: "Thunder",
            icon: "/mighty-decks/counters/energy.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/672/672776_1357949-hq.mp3",
                volume: 1,
                offsetMs: 0,
                durationMs: 7500,
            },
            lightEffect: {
                r: 255,
                g: 128,
                b: 255,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Lightning,
                animationDuration: 7500,
            },
        },
        fireplace: {
            slug: "Fireplace",
            title: "Fireplace",
            icon: "/mighty-decks/effects/burning.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/387/387128_7252788-hq.mp3",
                volume: 1,
                offsetMs: 0,
                durationMs: 20000,
            },
            lightEffect: {
                r: 255,
                g: 20,
                b: 0,
                intensity: 1,
                mode: LightModeEnum.Static,
                interval: 0,
                animation: AnimationEnum.Fireplace,
                animationDuration: 20000,
            },
        },
        ambulance: {
            slug: "Ambulance",
            title: "Ambulance",
            icon: "/mighty-decks/types/effect.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/94/94636_8043-hq.mp3",
                volume: 1,
                offsetMs: 0,
                durationMs: 5000,
                fadeInMs: 1000,
                fadeOutMs: 1000,
            },
            lightEffect: {
                r: 255,
                g: 0,
                b: 0,
                intensity: 0,
                mode: LightModeEnum.Flash,
                interval: 0,
                animation: AnimationEnum.Ambulance,
                animationDuration: 5000,
            },
        },
        police: {
            slug: "Police",
            title: "Police",
            icon: "/mighty-decks/stunts/escapist.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/692/692524_5828667-hq.mp3",
                volume: 1,
                offsetMs: 0,
                durationMs: 5000,
                fadeInMs: 1000,
                fadeOutMs: 1000,
            },
            lightEffect: {
                r: 255,
                g: 0,
                b: 0,
                intensity: 0,
                mode: LightModeEnum.Flash,
                interval: 0,
                animation: AnimationEnum.Police,
                animationDuration: 5000,
            },
        },
        gatling: {
            slug: "Gatling",
            title: "Gatling",
            icon: "/mighty-decks/assets/base/repeating_weapon.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/104/104404_1752241-hq.mp3",
                volume: 0.5,
                offsetMs: 0,
                durationMs: 4000,
                fadeInMs: 1000,
                fadeOutMs: 1000,
            },
            lightEffect: {
                r: 255,
                g: 0,
                b: 0,
                intensity: 0,
                mode: LightModeEnum.Flash,
                interval: 0,
                animation: AnimationEnum.Gatling,
                animationDuration: 4000,
            },
        },
        tension: {
            slug: "Tension",
            title: "Tension",
            icon: "/mighty-decks/stunts/hidden-arsenal.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/828/828570_17278148-hq.mp3",
                volume: 0.5,
                offsetMs: 0,
                durationMs: 34000,
                fadeInMs: 1000,
                fadeOutMs: 1000,
                previousFadeOutMs: 1000,
                channel: "MUSIC",
            },
        },
        epicorchestra: {
            slug: "EpicOrchestra",
            title: "Epic Orchestra",
            icon: "/mighty-decks/stunts/master-of-disguise.png",
            soundEffect: {
                url: "https://cdn.freesound.org/previews/250/250856_4146089-hq.mp3",
                volume: 0.5,
                offsetMs: 0,
                durationMs: 45714.3,
                fadeInMs: 1000,
                fadeOutMs: 1000,
                previousFadeOutMs: 1000,
                channel: "MUSIC",
            },
        },
    },
});

export const initialEffectBoardState: EffectBoardStateType = getInitialEffectBoardState();
