// This file is auto-generated by scripts/generate-encounters-meta.js
// Do not edit this file directly.

import { EncounterDefinition } from "./index";

export const encountersMap: { [key: string]: EncounterDefinition } = {
    "TTT-info": {
        "slug": "TTT-info",
        "path": "TTT-info",
        "title": "Trauma Team Troubles",
        "campaign": "Trauma Team Troubles"
    },
    "TOH-c1-a2-On-The-Road-to-Spice": {
        "slug": "TOH-c1-a2-On-The-Road-to-Spice",
        "path": "TOH-c1-a2-On-The-Road-to-Spice",
        "title": "Act 2 - On the road to Spice",
        "campaign": "Throne of Hawthorn",
        "chapter": 1
    },
    "TOH-c1-a1-Audience-with-the-king": {
        "slug": "TOH-c1-a1-Audience-with-the-king",
        "path": "TOH-c1-a1-Audience-with-the-king",
        "title": "Act 1 - At the king's court",
        "campaign": "Throne of Hawthorn",
        "chapter": 1
    },
    "TOH-c0-a0-GM-Info": {
        "slug": "TOH-c0-a0-GM-Info",
        "path": "TOH-c0-a0-GM-Info",
        "title": "Throne of Hawthorn - Game Master Info",
        "campaign": "Throne of Hawthorn"
    },
    "Rules": {
        "slug": "Rules",
        "path": "Rules",
        "title": "Test"
    },
    "PZZ-akt1-Intro": {
        "slug": "PZZ-akt1-Intro",
        "path": "PZZ-akt1-Intro",
        "title": "Pomsta ze Záhrobí",
        "campaign": "Pomsta ze Záhrobí",
        "chapter": 1
    },
    "PH-en-though-shalt-not-prank": {
        "slug": "PH-en-though-shalt-not-prank",
        "path": "PH-en-though-shalt-not-prank",
        "title": "Thou Shalt Not Prank",
        "campaign": "Hussite chronicles"
    },
    "PH-en-the-hidden-hand-of-strahov-scenes": {
        "slug": "PH-en-the-hidden-hand-of-strahov-scenes",
        "path": "PH-en-the-hidden-hand-of-strahov-scenes",
        "title": "The Hidden Hand of Strahov - Scenes",
        "campaign": "Hussite chronicles"
    },
    "PH-en-the-hidden-hand-of-strahov-info": {
        "slug": "PH-en-the-hidden-hand-of-strahov-info",
        "path": "PH-en-the-hidden-hand-of-strahov-info",
        "title": "The Hidden Hand of Strahov",
        "campaign": "Hussite chronicles"
    },
    "PH-en-penance-in-blood": {
        "slug": "PH-en-penance-in-blood",
        "path": "PH-en-penance-in-blood",
        "title": "Penance in Blood",
        "campaign": "Příběhy Husitů"
    },
    "PH-cs-stiny-klastera": {
        "slug": "PH-cs-stiny-klastera",
        "path": "PH-cs-stiny-klastera",
        "title": "Stíny Kláštera",
        "campaign": "Příběhy Husitů"
    },
    "PH-cs-nenapalis-blizniho-sveho": {
        "slug": "PH-cs-nenapalis-blizniho-sveho",
        "path": "PH-cs-nenapalis-blizniho-sveho",
        "title": "Nenapálíš bližního svého",
        "campaign": "Hussite chronicles"
    },
    "Oscaru-no-machi-rules": {
        "slug": "Oscaru-no-machi-rules",
        "path": "Oscaru-no-machi-rules",
        "title": "Oscaru no Machi - rozšíření"
    },
    "OS-en-radicare-rapid-rescue": {
        "slug": "OS-en-radicare-rapid-rescue",
        "path": "OS-en-radicare-rapid-rescue",
        "title": "RadiCare Rapid Rescue",
        "campaign": "One Shots"
    },
    "OS-en-low-key-heroes": {
        "slug": "OS-en-low-key-heroes",
        "path": "OS-en-low-key-heroes",
        "title": "Low-key Heroes",
        "campaign": "One Shots"
    },
    "OS-en-drink-till-your-luck-runs-out": {
        "slug": "OS-en-drink-till-your-luck-runs-out",
        "path": "OS-en-drink-till-your-luck-runs-out",
        "title": "Drink Till Your Luck Runs Out",
        "campaign": "One Shots"
    },
    "OS-cs-pij-nez-se-karta-obrati": {
        "slug": "OS-cs-pij-nez-se-karta-obrati",
        "path": "OS-cs-pij-nez-se-karta-obrati",
        "title": "Pij, než se karta obrátí",
        "campaign": "One Shots"
    },
    "ML-cs-c1-Slavnosti-stribra": {
        "slug": "ML-cs-c1-Slavnosti-stribra",
        "path": "ML-cs-c1-Slavnosti-stribra",
        "title": "Slavnosti Stříbra",
        "campaign": "Matečná žíla"
    },
    "ML-cs-c0-Info": {
        "slug": "ML-cs-c0-Info",
        "path": "ML-cs-c0-Info",
        "title": "Matečná žíla",
        "campaign": "Matečná žíla"
    },
    "LP-items": {
        "slug": "LP-items",
        "path": "LP-items",
        "title": "Běžné předměty",
        "campaign": "Ledová pomsta"
    },
    "LP-en-c2-a2-Spore-ship": {
        "slug": "LP-en-c2-a2-Spore-ship",
        "path": "LP-en-c2-a2-Spore-ship",
        "title": "Chapter 2 - Act 2 - Spore Ship",
        "campaign": "Cold Revenge",
        "chapter": 2
    },
    "LP-en-c2-a1-Departure": {
        "slug": "LP-en-c2-a1-Departure",
        "path": "LP-en-c2-a1-Departure",
        "title": "Chapter 2 - Act 1 - Departure",
        "campaign": "Cold Revenge",
        "chapter": 2
    },
    "LP-en-c1-a5-Boarding": {
        "slug": "LP-en-c1-a5-Boarding",
        "path": "LP-en-c1-a5-Boarding",
        "title": "Chapter 1 - Act 5 - Boarding",
        "campaign": "Cold Revenge",
        "chapter": 1
    },
    "LP-en-c1-a4-On-the-street": {
        "slug": "LP-en-c1-a4-On-the-street",
        "path": "LP-en-c1-a4-On-the-street",
        "title": "Chapter 1 - Act 4 - On the Street",
        "campaign": "Cold Revenge",
        "chapter": 1
    },
    "LP-en-c1-a3-Partys-over": {
        "slug": "LP-en-c1-a3-Partys-over",
        "path": "LP-en-c1-a3-Partys-over",
        "title": "Chapter 1 - Act 3 - Party's over",
        "campaign": "Cold Revenge",
        "chapter": 1
    },
    "LP-en-c1-a2-Celebration": {
        "slug": "LP-en-c1-a2-Celebration",
        "path": "LP-en-c1-a2-Celebration",
        "title": "Chapter 1 - Act 2 - Celebration of Victory",
        "campaign": "Cold Revenge",
        "chapter": 1
    },
    "LP-en-c1-a1-Return": {
        "slug": "LP-en-c1-a1-Return",
        "path": "LP-en-c1-a1-Return",
        "title": "(Summary for GM: Mission to rescue the Clan Gynie research team on the planet Sporefall)",
        "campaign": "Cold Revenge",
        "chapter": 1
    },
    "LP-en-c0-a0-Info": {
        "slug": "LP-en-c0-a0-Info",
        "path": "LP-en-c0-a0-Info",
        "title": "Cold Revenge",
        "campaign": "Cold Revenge"
    },
    "LP-c2-a2-Sporova-lod": {
        "slug": "LP-c2-a2-Sporova-lod",
        "path": "LP-c2-a2-Sporova-lod",
        "title": "Kapitola 2&nbsp;- Akt 2&nbsp;- Spórová Loď",
        "campaign": "Ledová pomsta",
        "chapter": 2
    },
    "LP-c2-a1-Vysadek": {
        "slug": "LP-c2-a1-Vysadek",
        "path": "LP-c2-a1-Vysadek",
        "title": "Kapitola 2&nbsp;- Akt 1 - Výsadek",
        "campaign": "Ledová pomsta",
        "chapter": 2
    },
    "LP-c1-a5-Odlet": {
        "slug": "LP-c1-a5-Odlet",
        "path": "LP-c1-a5-Odlet",
        "title": "Kapitola 1 - Akt 5 - Odlet",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "LP-c1-a4-Na-ulici": {
        "slug": "LP-c1-a4-Na-ulici",
        "path": "LP-c1-a4-Na-ulici",
        "title": "Kapitola 1 - Akt 4 - Na ulici",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "LP-c1-a3-Partys-over": {
        "slug": "LP-c1-a3-Partys-over",
        "path": "LP-c1-a3-Partys-over",
        "title": "Kapitola 1 - Akt 3&nbsp;- Party's over",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "LP-c1-a2-Oslava": {
        "slug": "LP-c1-a2-Oslava",
        "path": "LP-c1-a2-Oslava",
        "title": "Kapitola 1 - Akt 2&nbsp;- Oslava vítězství",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "LP-c1-a1-Navrat": {
        "slug": "LP-c1-a1-Navrat",
        "path": "LP-c1-a1-Navrat",
        "title": "(Shrnutí pro GM: Mise na záchranu výzkumného týmu Klanu Gynies na planetě Sporefall)",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "LP-c0-a0-Info": {
        "slug": "LP-c0-a0-Info",
        "path": "LP-c0-a0-Info",
        "title": "Ledová pomsta",
        "campaign": "Ledová pomsta"
    },
    "LP-akt1-Vyzkumnice": {
        "slug": "LP-akt1-Vyzkumnice",
        "path": "LP-akt1-Vyzkumnice",
        "title": "Výzkumnice klanu",
        "campaign": "Ledová pomsta",
        "chapter": 1
    },
    "KJB-act1-01-Intro": {
        "slug": "KJB-act1-01-Intro",
        "path": "KJB-act1-01-Intro",
        "title": "Město v plamenech",
        "campaign": "Království Jediné Bohyně",
        "chapter": 1
    },
    "ISV-c1-a0-Info": {
        "slug": "ISV-c1-a0-Info",
        "path": "ISV-c1-a0-Info",
        "title": "In Sanguine Veritas",
        "campaign": "In Sanguine Veritas"
    },
    "ISV-c0-a1-Prequel": {
        "slug": "ISV-c0-a1-Prequel",
        "path": "ISV-c0-a1-Prequel",
        "title": "In Sanguine Veritas - Prequel",
        "campaign": "In Sanguine Veritas"
    },
    "ISV-c0-a0-Prequel-GM-Info": {
        "slug": "ISV-c0-a0-Prequel-GM-Info",
        "path": "ISV-c0-a0-Prequel-GM-Info",
        "title": "In Sanguine Veritas - Informace pro vypravěče (obsahuje spoilery)",
        "campaign": "In Sanguine Veritas"
    },
    "index": {
        "slug": "index",
        "path": "index",
        "title": "Featured Encounters [CS](index-cs)"
    },
    "index-cs": {
        "slug": "index-cs",
        "path": "index-cs",
        "title": "Vybraná Dobrodružství [EN](index)"
    },
    "B139-rules-cs": {
        "slug": "B139-rules-cs",
        "path": "B139-rules-cs",
        "title": "Futuristický LARP",
        "campaign": "B-day"
    },
    "B139-info-cs": {
        "slug": "B139-info-cs",
        "path": "B139-info-cs",
        "title": "B-Day #139: Futuristický LARP",
        "campaign": "B-day"
    },
    "exiles-of-the-hungry-void/c1-transport-in-distress": {
        "slug": "exiles-of-the-hungry-void/c1-transport-in-distress",
        "path": "exiles-of-the-hungry-void/c1-transport-in-distress",
        "title": "A transport in distress",
        "campaign": "Exiles of the Hungry Void",
        "chapter": 1
    },
    "exiles-of-the-hungry-void/c1-mining-colony-has-a-pest-problem": {
        "slug": "exiles-of-the-hungry-void/c1-mining-colony-has-a-pest-problem",
        "path": "exiles-of-the-hungry-void/c1-mining-colony-has-a-pest-problem",
        "title": "Mining Colony Has a Pest Problem",
        "campaign": "Exiles of the Hungry Void",
        "chapter": 1
    },
    "exiles-of-the-hungry-void/c1-graveyard-bazaar": {
        "slug": "exiles-of-the-hungry-void/c1-graveyard-bazaar",
        "path": "exiles-of-the-hungry-void/c1-graveyard-bazaar",
        "title": "Graveyard Bazaar",
        "campaign": "Exiles of the Hungry Void",
        "chapter": 1
    },
    "exiles-of-the-hungry-void/c1-dead-in-space": {
        "slug": "exiles-of-the-hungry-void/c1-dead-in-space",
        "path": "exiles-of-the-hungry-void/c1-dead-in-space",
        "title": "Dead in space",
        "campaign": "Exiles of the Hungry Void",
        "chapter": 1
    },
    "exiles-of-the-hungry-void/c1-abandoned-research-station": {
        "slug": "exiles-of-the-hungry-void/c1-abandoned-research-station",
        "path": "exiles-of-the-hungry-void/c1-abandoned-research-station",
        "title": "An Abandoned Research Station",
        "campaign": "Exiles of the Hungry Void",
        "chapter": 1
    },
    "exiles-of-the-hungry-void/c0-intro": {
        "slug": "exiles-of-the-hungry-void/c0-intro",
        "path": "exiles-of-the-hungry-void/c0-intro",
        "title": "Exiles of the Hungry Void",
        "campaign": "Exiles of the Hungry Void"
    }
};
